### ISSUE TITLE
[tasklist] feat: design and implement context menu for resumes in gallery

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#100]
**Description**

We want to support a list of context operations for sample resumes in gallery page. For example, user can:

- download the resume PDF
- download the resume tex source code
- fork the resume and create their own, **this is the most useful one**
- zoom in and preview the resume

**[Optional] Possible solutions**

NA

**Acceptance Criteria**

- resumes in gallery page show allow a list of context operations

**Todo list**

```[tasklist]
- [x] feat: download the resume PDF in gallery page
- [ ] feat: download the resume tex source code in gallery page
- [ ] fork the resume and create their own in gallery page
- [ ] zoom in and preview the resume in gallery page
```
