### ISSUE TITLE
[tasklist] doc: add manual for content -> multi languages

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#110]
## Description

Add a section with path: content -> multi languages.

The section will decribe PPResume native support for multi languages resumes.

## Todo list

```[tasklist]
### Tasks
- [ ] https://github.com/ppresume/community/issues/111
- [ ] https://github.com/ppresume/community/issues/112
- [ ] https://github.com/ppresume/community/issues/113
- [ ] https://github.com/ppresume/community/issues/114
- [ ] https://github.com/ppresume/community/issues/115
- [ ] https://github.com/ppresume/community/issues/116
```

**Comment by xiaohanyu** [comment]
The landing page for `content -> multi languages`:

<img width="2672" alt="image" src="https://github.com/user-attachments/assets/5ce2ea34-7814-4cea-93e9-50c02794f95d">
