### ISSUE TITLE
[tasklist] feat: open source PPResume typesetting engine

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#121]
## Description

We decided to open source our typesetting engine so advanced users have a complete and free version of PPResume that can be run on their devices, offline.

A similar project: [rendercv](https://github.com/sinaatalay/rendercv)

## [Optional] Possible Solutions

NA

## Acceptance Criteria

- open source PPResume typesetting engine
- get a CLI
- publish it to npmjs

## Todo list

- [x] README.md
  - [x] installation instructions
  - [x] usage examples
  - [x] screenshots and demo
  - [x] technology used
- [x] CONTRIBUTING.md
- [x] code comments
- [x] improve test coverage
- [x] CI
  - [x] `pnpm build`
  - [x] `pnpm lint`
  - [x] `pnpm release`
  - [x] `pnpm publish`
  - [x] github actions for test and publish

**Comment by xiaohanyu** [comment]
All done. 

Created a new project: https://github.com/yamlresume/yamlresume
