### ISSUE TITLE
[tasklist] feat: adopt PWA phase 1

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#37]
## Description

[PWA](https://web.dev/articles/what-are-pwas) is a suite of APIs and patterns the can bring app like experience for modern web.

We want to adopt PWA techniques bit by bit to provide a better experience for PPResume.

## [Optional] Possible Solutions

NA

## Acceptance Criteria

- User can install PPResume to their desktop/home on laptop/phones and has a app like experience

## Todo list

```[tasklist]
- [ ] https://github.com/ppresume/community/issues/38
- [ ] https://github.com/ppresume/community/issues/41
- [ ] https://github.com/ppresume/community/issues/42
- [ ] https://github.com/ppresume/community/issues/43
- [ ] https://github.com/ppresume/community/issues/47
```
