### ISSUE TITLE
[tasklist] feat: resume i18n and l10n stage 1

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#4]
## Description

Even though we already support basic CJK input for resumes and PDF output, we havn't completed 100% support for CJK yet. For example, some options for degree input (`Bachelor`, `Master` etc), language level input (`Elementary Proficiency`, `Limited Working Proficiency` etc) has not been translated when you want to pure CJK resume.

Besides, different language may need different format for dates as well.

## Acceptance Criteria

- the settings drawer should support a new option: `Language`, where user can set preferred locale for a resume.
- the date format and other options should respect the `Language` settings for the resume.

## Todo list

```[tasklist]
- [x] https://github.com/ppresume/community/issues/61
- [x] https://github.com/ppresume/community/issues/62
- [x] https://github.com/ppresume/community/issues/63
- [x] section name translation
- [x] datetime localization
- [x] language name and fluency translation
- [x] education degrees translation
- [x] skills level translation
- [x] "Keywords" translation
- [x] "Courses" translation
- [x] fix separator in `cvlanguage` command
- [x] Location translation
```

**Comment by xiaohanyu** [comment]
This was finally done, spent about 10 days overall on this. Now we have a foundational setup to support i18n and l10n for resumes. As of now, we support English, Simplified Chinese and Traditional Chinese resumes, but it won't be too hard to add more languages. Some preview:

![image](https://github.com/ppresume/community/assets/1164623/23ea9edd-4396-41d6-9ff0-c301a2392e01)
![image](https://github.com/ppresume/community/assets/1164623/921ea395-ef0a-409f-b4e2-45ec6d33197c)
![image](https://github.com/ppresume/community/assets/1164623/ccde8b8f-fb3a-46b0-9e21-df42b1c0f305)
![image](https://github.com/ppresume/community/assets/1164623/7e089fdc-ee90-41e6-a32d-1dbe2072e291)
![image](https://github.com/ppresume/community/assets/1164623/e9d4b755-4248-4903-8d66-6058bf690efa)
