### ISSUE TITLE
feat: adopt google workbox to init PWA setup

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#41]
## Description

[workbox](https://web.dev/learn/pwa/workbox) seems to be the defac to way to enable PWA for a web site. We want to integrate it and avoid re-invent wheels.

## [Optional] Possible Solutions

- adopt [next-pwa](https://github.com/shadowwalker/next-pwa), however this project seems not actively maintained any more, it has [issue](https://github.com/shadowwalker/next-pwa/issues/504) with next.js 14
- adopt [serwist](https://serwist.pages.dev), which is a revised fork of workbox and provides [next.js support](https://serwist.pages.dev/docs/next)

## Acceptance Criteria

- setup workbox with PPResume workflow

## Todo list

```[tasklist]
### Tasks
- [x] decide which lib/framework to use for PWA adoption
- [x] install necessary libs to project
- [x] check debug/production environment difference
```

**Comment by xiaohanyu** [comment]
We decided to use [serwist](https://serwist.pages.dev), reasons:

- it is actively maintained
- next-pwa's development has been stopped for 2 years
- adopt raw workbox requires too much labor.

**Comment by xiaohanyu** [comment]
There're some difference for cache behaviour when `process.env.NODE_ENV` is switching from `development` to `production`

- the cache storage won't be populated when `process.env.NODE_ENV` is `development`, check code [here](https://github.com/serwist/serwist/blob/89d51fd/packages/next/src/worker/defaultCache.ts#L13-L15)

**Comment by xiaohanyu** [comment]
Overall [serwist](https://serwist.pages.dev/) is pretty good, though its docs is not very complete.
