### ISSUE TITLE
feat: set up proper web manifest for PWA preparation

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#42]
## Description

A web app manifest is a JSON file that tells the browser how your Progressive Web App (PWA) should behave when installed on the user's desktop or mobile device.

Let's set up proper mantifest for PPResume PWA.

Ref:
- https://web.dev/articles/add-manifest
- https://developer.mozilla.org/en-US/docs/Web/Manifest

## [Optional] Possible Solutions

- manually setup manifest
- setup manifest via google workbox

## Acceptance Criteria

- setup proper manifest for PPResume PWA

## Todo list

```[tasklist]
### Tasks
- [x] setup proper manifest file
- [x] ~setup proper twitter share tags~
- [x] ~setup proper facebook share tags~
- [x] cache manifest files (images, icons) in service worker precache
```

**Comment by xiaohanyu** [comment]
Twitter card and facebook's open graph tags need to be generated dynamically for some page.

This could be done by integration [next-seo](https://github.com/garmeeh/next-seo) or migrating to [generateMetaData](https://nextjs.org/docs/app/api-reference/functions/generate-metadata) from next.js 13+'s app router.

We will hold this for a while.

**Comment by xiaohanyu** [comment]
Done.

![Image](https://github.com/ppresume/community/assets/1164623/ae7ae390-463d-410a-9b9f-c2f40814c432)

![Image](https://github.com/ppresume/community/assets/1164623/52abc58d-682e-48cd-b8df-c9aed5259bbd)

Potential further optimization:

- #46
