### ISSUE TITLE
feat: set up service worker for PWA

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#43]
## Description

Service worker sit at the core of a PWA app and we need to set up service worker when adopt PWA for PPResume.

This issue depends on #41 and is depended by #39 

## [Optional] Possible Solutions

- manually setup service worker
- use workbox to generate a service worker

## Acceptance Criteria

- let's use workbox to generate a service worker for PPResume

## Todo list

```[tasklist]
### Tasks
- [x] setup service-worker
- [x] setup correct caching strategy for different resources
- [x] make sure the app works the same with or without service worker cache (i.e, progressive enhancement)
- [x] check cachebility for cors request to unpkg
- [x] set cache quota and check cache eviction strategy
```

**Comment by xiaohanyu** [comment]
Done.

Preview:

![Image](https://github.com/ppresume/community/assets/1164623/a0c1c7da-d4a9-4688-af48-56cbded68401)
