### ISSUE TITLE
[tasklist] feat: accessibility compliance

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#72]
**Description**

Accessible Rich Internet Applications (ARIA) is a set of [roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles) and [attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes) that define ways to make web content and web applications (especially those developed with JavaScript) more accessible to people with disabilities.

Ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**[Optional] Possible solutions**
None

**Todo list**

```[tasklist]
- [ ] Read MDN articles
- [ ] check mantine's support for ARIA
- [ ] Create issues to support ARIA for PPResume
```

**Comment by xiaohanyu** [comment]
Valuable resources:
- https://www.w3.org/WAI/ARIA/apg/patterns/
- https://www.radix-ui.com/primitives/docs/overview/introduction
