### ISSUE TITLE
feat: auth: reset password for account

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#9]
## Description

As title, sometimes user need to reset password

## [Optional] Possible solutions

- send reset password OTP by email
- send reset password OTP by phone

## Acceptance Criteria

- user should be able to reset his password successfully with OTP
- we decided to adopt emails for sending OTPs

## Todo list

```[tasklist]
- [ ] check email providers
- [ ] design email template
- [ ] implement the logic
```

**Comment by xiaohanyu** [comment]
Deprecated and archived in favor of https://github.com/ppresume/ppresume/issues/135
