### ISSUE TITLE
[tasklist] feat: adopt PWA phase 2

### ISSUE THREAD

**Issue by xiaohanyu** [ppresume/community#92]
## Description

This is a follow up issue for https://github.com/ppresume/community/issues/37. 

## [Optional] Possible Solutions

NA

## Acceptance Criteria

- User can install PPResume to their desktop/home on laptop/phones and has a app like experience

## Todo list

```[tasklist]
- [ ] https://github.com/ppresume/community/issues/38
- [ ] https://github.com/ppresume/community/issues/41
- [ ] https://github.com/ppresume/community/issues/42
- [ ] https://github.com/ppresume/community/issues/43
- [ ] https://github.com/ppresume/community/issues/46
- [ ] https://github.com/ppresume/community/issues/47
- [ ] https://github.com/ppresume/community/issues/48
- [ ] https://github.com/ppresume/community/issues/49
- [ ] https://github.com/ppresume/community/issues/50
```
